### ISSUE TITLE
S3 event info is not being reported

### ISSUE THREAD

**Issue by adjohn** [iopipe/iopipe-js-event-info#34]
S3 triggers are not being reported by this plugin currently.  

**For IOpipe internal team:** 
I setup a test function which you can see here: https://dashboard.iopipe.com/project/74849dec-5fd2-44a1-a15b-8120155cc965/functions/arn:aws:lambda:us-east-1:554407330061:function:serverlessrepo-adam-s3-lambda-ConvertFileFunction-1J7VP3DPP5YD/invocation/AWpr0V1yhGw1YpGuwOnh#search=func%3D%22serverlessrepo-adam-s3-lambda-ConvertFileFunction-1J7VP3DPP5YD%22%20requestId%3D%22ad5baa90-01a4-4ada-a760-d62cba16e221%22&timeframe=15m

The data in our internal DB also does not show S3 event info being stored/reported.

This invocation was triggered by an S3 file upload event.

**Comment by adjohn** [comment]
Debug output from a function triggered by S3 

`2019-05-01T00:25:21.590Z	6cf1463b-8185-401c-ad3d-0c725423ac67	IOPIPE-DEBUG: {"client_id":"eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI3NDg0OWRlYy01ZmQyLTQ0YTEtYTE1Yi04MTIwMTU1Y2M5NjUiLCJqdGkiOiJiNTA5NjM5NS0zNzA0LTRhY2EtOWVhZS1kMTZiNDliY2ZmZDAiLCJpYXQiOjE1MDIxMTgyOTUsImlzcyI6Imh0dHBzOi8vaW9waXBlLmNvbSIsImF1ZCI6Imh0dHBzOi8vaW9waXBlLmNvbSxodHRwczovL21ldHJpY3MtYXBpLmlvcGlwZS5jb20vZXZlbnQvLGh0dHBzOi8vZ3JhcGhxbC5pb3BpcGUuY29tIn0.XFIuRzQcpq-nu-ci3eJqq9dxShppWHINyvk1BYY2EqQ","installMethod":"manual","duration":5855171462,"processId":"b2bc2f38-88e8-44ab-abc8-f1e3d012f67a","timestamp":1556670315735,"aws":{"functionName":"upload-to-s3-and-postprocess-dev-postprocess","functionVersion":"$LATEST","awsRequestId":"6cf1463b-8185-401c-ad3d-0c725423ac67","invokedFunctionArn":"arn:aws:lambda:us-east-1:554407330061:function:upload-to-s3-and-postprocess-dev-postprocess","logGroupName":"/aws/lambda/upload-to-s3-and-postprocess-dev-postprocess","logStreamName":"2019/05/01/[$LATEST]90266dd580ba498fb97004ea0fc52a4c","memoryLimitInMB":"1024","getRemainingTimeInMillis":139,"traceId":"Root=1-5cc8e76b-22592f7e10d4cc4652d1fd9e;Parent=21960a9b421dbb82;Sampled=0"},"environment":{"agent":{"runtime":"nodejs","version":"1.17.2","load_time":1556670315722},"runtime":{"name":"node","version":"v8.10.0"},"nodejs":{"version":"v8.10.0","memoryUsage":{"rss":42369024,"heapTotal":19849216,"heapUsed":11288000,"external":570066}},"host":{"boot_id":"a6319e8e-9f78-49b0-b652-14a02c68ce2d"},"os":{"hostname":"169.254.221.165","uptime":1969,"totalmem":1221582848,"freemem":1065029632,"usedmem":156553216,"cpus":[{"model":"Intel(R) Xeon(R) Processor @ 2.50GHz","speed":2500,"times":{"user":4500,"nice":0,"sys":2300,"idle":19687200,"irq":0}},{"model":"Intel(R) Xeon(R) Processor @ 2.50GHz","speed":2500,"times":{"user":1700,"nice":0,"sys":2100,"idle":19691700,"irq":0}}],"arch":"x64","linux":{"pid":{"self":{"stat_start":{"utime":"14","stime":"7","cutime":"0","cstime":"0","rss":"10246"},"stat":{"utime":"14","stime":"7","cutime":"0","cstime":"0","rss":"10312"},"status":{"FDSize":64,"Threads":10,"VmRSS":41248}}}}}},"errors":{"name":"Error","message":"Timeout Exceeded.","stack":"Error: Timeout Exceeded.\n at Timeout._onTimeout (/opt/nodejs/node_modules/@iopipe/core/dist/iopipe.js:1750:38)\n at ontimeout (timers.js:482:11)\n at tryOnTimeout (timers.js:317:5)\n at Timer.listOnTimeout (timers.js:277:5)"},"coldstart":true,"custom_metrics":[],"labels":["@iopipe/timeout","@iopipe/error","@iopipe/coldstart"],"plugins":[{"name":"@iopipe/trace","version":"1.3.0","homepage":"https://github.com/iopipe/iopipe-plugin-trace#readme","uploads":[]},{"name":"@iopipe/event-info","version":"1.3.0","homepage":"https://github.com/iopipe/iopipe-js-event-info#readme","uploads":[]}],"httpTraceEntries":[],"timestampEnd":1556670321590}
`
